### ISSUE TITLE
Is Azurite supported?

### ISSUE THREAD

**Issue by yooakim** [duckdb/ducklake#161]
This is probably a user error :-)

I am trying to setup a local development environment. Our infra is in Azure and for local development and testing we use Azurite. I  running in a Docker container (started via Docker compose)

The I try this DuckDB CLI (version v1.3.0 71c5c07cdd) :
```
INSTALL ducklake;
INSTALL sqlite;
INSTALL azure;
LOAD azure;

# Secret for the devstoreaccount, well known key etc
CREATE SECRET secret (
      TYPE AZURE,
      CONNECTION_STRING 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;'
  );

ATTACH 'ducklake:postgres:dbname=postgres host=localhost user=postgres password=password' AS my_ducklake (DATA_PATH 'az://ducklake/');


CREATE TABLE nl_train_stations AS
      FROM 'https://blobs.duckdb.org/nl_stations.csv';
```

But nothing ends up in my Azure container.

I have verified my connection to Azurite from my local host and I can list files in my container using `FROM GLOB('az://ducklake/*.txt');`

So I guess my question is; Should this work?

My compse.yml file contains the following:
```
services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ducklake_catalog
      POSTGRES_USER: ducklake_catalog
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - ducklake-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - ducklake-network

  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: storage
    restart: unless-stopped
    ports:
      - 10000:10000  # Blob service
      - 10001:10001  # Queue service
      - 10002:10002  # Table service
    networks:
      - ducklake-network
    volumes:
      - azurite_data:/data

networks:
  ducklake-network:
    driver: bridge

volumes:
  postgres_data:
  azurite_data:

```
